name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    if: github.ref != 'refs/heads/builds'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "src"

      - name: Checkout builds branch
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "builds"

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Clean Gradle build cache
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew clean

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds || true

      - name: Push builds to builds branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Build ${GITHUB_SHA::7}" || exit 0
          git push origin HEAD:builds --force
